### ISSUE TITLE
Remove "2019_02_11_001152_add_tournament_id_to_matches_table.php"

### ISSUE THREAD

**Issue by MattiaLimone** [Barsnes/QuixzLaravel#2]
tournament_id already exist in "2018_12_10_021113_create_matches_table.php"

**Comment by Barsnes** [comment]
Hi, 

This must have been overlooked while connecting matches to tournaments. I have removed the migration in my [latest commit](https://github.com/Barsnes/QuixzLaravel/commit/43acb1ffe9135d94cd59e65912daec09667d290f).

Thanks!
